### ISSUE TITLE
Include subdirectory?

### ISSUE THREAD

**Issue by mclearc** [pprevos/citar-denote#11]
I put my notes for denote in various subdirectories. It would be nice to add this as an option for citar-denote. You could do something like this for `citar-denote-create-note`

```emacs-lisp
(defun citar-denote-create-note (key &optional _entry)
  "Create a bibliography note for `KEY' with properties `ENTRY'.
The file type for the note to be created is determined by user
option `denote-file-type'."
  (let ((denote-file-type citar-denote-file-type))
    (denote
     (read-string "Title: " (citar-get-value "title" key))
     (citar-denote-keywords-prompt))
    (citar-denote-add-reference key denote-file-type)
    (when denote-subdir (denote-subdirectory-prompt))))
```

I'm not sure if other functions would also need to be changed for note retrieval, etc.

**Comment by pprevos** [comment]
Hi Colin, I am about release a new version (which allows multiple notes per entry and multiple entries per note), so I am happy to weave this in as well.

What is the `denote-subdir` variable?

**Comment by pprevos** [comment]
Another question. I don't use subdirectories so cannot test your suggestion. 

When you use multiple folders, does the `denote-directory-files-matching-regexp` function list all notes in all folders? I use this function to check for reference keys.

**Comment by mclearc** [comment]
> What is the denote-subdir variable?

That was just a dummy variable for the sample function I gave above. I figure since not everyone uses subdirs better to have the option to not show the subdir prompt. 

> When you use multiple folders, does the denote-directory-files-matching-regexp function list all notes in all folders? 

As far as I can tell it does. I haven't tested it extensively but it picks up the references that are properly formatted in my `refs-dir` subdirectory.

**Comment by pprevos** [comment]
I'll have to read the Denote manual how it treats subdirs, It is certainly feasible, Only two functions in citar-denote are directory-specific.

**Comment by pprevos** [comment]
I think it is as easy as you indicated. I added:

```
(defcustom citar-denote-subdir 't
  "Ask for a subdirectory when creating a new bibliographic note.")
```

And changed the creation function as suggested:

```
(defun citar-denote-create-note (key &optional _entry)
  "Create a bibliography note for `KEY' with properties `ENTRY'.

The file type for the note to be created is determined by `denote-file-type'.
When `citar-denote-subdir' is non-nil, prompt for a subdirectory."
  (denote
   (read-string "Title: " (citar-get-value "title" key))
   (citar-denote-keywords-prompt)
   citar-denote-file-type
   (when citar-denote-subdir (denote-subdirectory-prompt)))
  (citar-denote-add-reference key citar-denote-file-type))
```
Can you test and confirm that this is what you need? If so, then I will commit the new version.

**Comment by mclearc** [comment]
Yes -- that works well! Thanks!

**Comment by pprevos** [comment]
Excellent - I have pushed this version.
