### ISSUE TITLE
Author (year) as title

### ISSUE THREAD

**Issue by adrianadermon** [pprevos/citar-denote#15]
Hi,

is it possible to change the title of the note? In my field, we tend to talk about papers as "author (year)", with the consequence that we rarely know the titles of papers. However, citar-denote uses the title of the paper as the title of the note, and as far as I can tell there's no way to change this. 

I think it would be really nice to have the option of customizing this. Can this be done? If not, are there any plans to add it?

**Comment by pprevos** [comment]
Hi Adrian,

This can certainly be done with an option.

The only slightly complex issue is the author name. 

Citar only gives the full name, e.g. Adermon, Adrian. 

This means I need a cleaning function (which could be useful in Citar as well). I assume you need: "Adermon (2023)" (1 author) or "Adermon and Prevos (2023)" (2 authors) or "Adermon et al. (2023)" (3 or more authors). 

Such a function could be useful for Citar as well, ping @bdarcus.

P:)

**Comment by bdarcus** [comment]
> Citar only gives the full name, e.g. Adermon, Adrian.

Try this function:

```elisp
(citar--shorten-names "Doe, Jane and Smith, Joan")
```

**Comment by pprevos** [comment]
Thanks @bdarcus, that is a great. The word "and" could possibly be a variable as it is language-dependent.

@adrianadermon , can you please try this function on some of your citekeys?

```
(defun citar-denote-extract-author-year (citekey)
  "Extract author (year) from CITEKEY."
  (let* ((author-full (citar-get-value "author" citekey))
	 (author-full (if (not author-full)
			  (citar-get-value "editor" citekey)
			author-full))
	 (author (citar--shorten-names author-full))
	 (year (citar-get-value "year" citekey)))
    (concat author " (" year ")")))
```

**Comment by adrianadermon** [comment]
Thanks for the quick reply @pprevos, @bdarcus! This is great, but there are two things that could make it even better. 

First, I'd love to be able to shorten it when there are many coauthors (say, more than two) to "Adermon, pprevos et al. (2023)". 

Second, for two or more authors, it gives me a comma-separated list: "Adermon, pprevos (2023)", but ideally it would be "Adermon & pprevos (2023)". For more than two authors (and assuming no et al.), it would be "Adermon, bdarcus & pprevos (2023)".

**Comment by pprevos** [comment]
I just completed an improved version that either gives:
- Author (year)
- Author1 and Author2 (year)
- Author1 et al. (year)

```
  (defun citar-denote-insert-author-year (citekey)
    "Extract author (year) from CITEKEY."
    (let* ((author-full (citar-get-value "author" citekey))
           (author-full (if (not author-full)
                            (citar-get-value "editor" citekey)
                          author-full))
           (names (citar--shorten-names author-full))
           (idv-names  (mapcar
                        (lambda (n) (replace-regexp-in-string "," "" n))
                        (split-string names)))
           (num-authors (length idv-names))
           (author (cond ((equal num-authors 1) names)
                         ((equal num-authors 2)
                          (concat (car idv-names) " and "
                                  (cadr idv-names)))
                         (t (concat (car idv-names) " et al."))))
           (year (citar-get-value "year" citekey)))
      (concat author " (" year ")")))
```

So far only works with BibTeX files, not quite yet with CSL files. Please give it a whirl.

**Comment by pprevos** [comment]
Refactored version that works on BibTeX and CSL:

```
  (defun citar-denote-insert-author-year (citekey)
    "Extract author (year) from CITEKEY."
    (let* ((author-full (or (citar-get-value "author" citekey)
                            (citar-get-value "editor" citekey)))
           (names (citar--shorten-names author-full))
           (idv-names  (mapcar
                        (lambda (n) (replace-regexp-in-string "," "" n))
                        (split-string names)))
           (num-authors (length idv-names))
           (author (cond ((equal num-authors 1) names)
                         ((equal num-authors 2)
                          (concat (car idv-names) " and "
                                  (cadr idv-names)))
                         (t (concat (car idv-names) " et al."))))
           (year (or (citar-get-value "year" citekey)
                     (citar-get-value "issued" citekey))))
      (concat author " (" year ")")))
```

**Comment by adrianadermon** [comment]
Works perfectly!

Only one more thing - since users might have different preferences for the number of authors to be shown before switching to "et al.", it might be nice to make it possible to change that number?

Regardless, thanks for being so responsive, and for making this great package!

**Comment by bdarcus** [comment]
I thought we had modified the citar function (which, BTW, is really designed for the minibuffer display) to enable et al as an option.

Regardless, I think the way to do that right is probably just to have an optional parameter whose value is an integer.

**Comment by bdarcus** [comment]
Ah, it was unresolved:

https://github.com/emacs-citar/citar/issues/694

**Comment by bdarcus** [comment]
> (year (or (citar-get-value "year" citekey)
>                      (citar-get-value "issued" citekey))))

You don't support biblatex here.

**Comment by fintelkai** [comment]
It would be great if the customization also allowed to choose the citekey itself as the title of the denote note. I'm already used to using the citekey in the filename for any associated pdfs and so on.

**Comment by pprevos** [comment]
> choose the citekey itself as the title

Sure, how about having that as the nil option and configure as such:

```
  (defcustom citar-denote-note-title "title"
    "Title for new bibliographic notes.
  - \"author-year\": Author-year citation style
  - \"title\": Extract title (or short title) from entry
  - \"full\": Full citation
  - nil: Citekey as-is"
    :group 'citar-denote
    :type  'string)
```

Not sure if this is the proper way to use `defcustom`, but it works.

**Comment by pprevos** [comment]
> don't support biblatex

@bdarcus , BibLaTex also uses the year field.

**Comment by bdarcus** [comment]
But it also, and I think prefers, `date`.

Can any of you test this PR and confirm it works as expected?

https://github.com/emacs-citar/citar/pull/732

**Comment by pprevos** [comment]
Thanks, I'll check it out this later. I am not so good with GitHub. How do I access the code? Can I clone the branch?

**Comment by bdarcus** [comment]
Yeah:

https://stackoverflow.com/questions/1911109/how-do-i-clone-a-specific-git-branch

**Comment by pprevos** [comment]
Hi Bruce, your function is great. Thanks for adding this upstream. I have integrated it with my code.

Will commit when your branch goes into citar main.

**Comment by bdarcus** [comment]
I just need to figure out how to adjust the citar template language so I can add it to `citar-org-roam`.

**Comment by pprevos** [comment]
Great work Bruce. I am doing the final testing for the new Citar-Denote, with a dependency on Citar 1.1.

**Comment by pprevos** [comment]
I have just committed the updated Citar-Denote package, including updated manual. Big thanks to Adrian and Kai for the suggestions and Bruce for updating Citar to enable this functionality.

62169f5533ae1155bbc63a846ce10cc2f4003e76

**Comment by bdarcus** [comment]
Preface: I created CSL, so am painfully aware of the complexities of all this. And @pprevos is right this is intended to be a lightweight solution.

Anyway, on the details, here's an example from such a CSL style:

```xml
 <bibliography et-al-min="4" et-al-use-first="1" entry-spacing="0" second-field-align="flush">
```

So already is has two parameters while this function only.

You can read the documentation of et-al handling here, which shows more than two parameters.

If you can come up with a reasonable way to extend the citar function (e.g. without too much complexity), we can consider that over there (in which case you can put in a feature request there).

https://docs.citationstyles.org/en/stable/specification.html#name

Note, however: one wrinkle that CSL processors handle, but this likely won't: disambiguation.

So what do you with these if you want only the first name?

```
Doe, J and Smith, K
Doe, J and Jones M
```

**Comment by andras-simonyi** [comment]
> Do you know if that's practical @andras-simonyi; to use citeproc only to format, for example, a list of author names?

Without being familiar with the context, I'd say it should be possible, IIRC Nicolas P. Rougier's [Literate & annotated bibliography mode](https://github.com/rougier/org-bib-mode/blob/master/org-bib.el) uses citeproc to render authors' names in previews.

**Comment by bdarcus** [comment]
Oh, perfect; thanks!

**Comment by bdarcus** [comment]
Actually, we already have ` citar-citeproc-format-reference`, which can do this. It would just need to allow an optional `style` argument, I think, so that one can use arbitrary styles, like the one that Nicolas uses for name formatting.

**Comment by pprevos** [comment]
I prefer to keep citation styling issues out of my package as much as possible and rather lean on a specialised package.

The current version will stay as-is until a more configurable solution is available from another package.

**Comment by bdarcus** [comment]
Yes; sorry if that was unclear. I've opened an issue in citar to address it there.

https://github.com/emacs-citar/citar/issues/737

**Comment by pprevos** [comment]
Thanks for all the help Bruce - and thanks for developing CSL.

**Comment by bdarcus** [comment]
Just a little update on the citar end.

I did merge a small change yesterday that allows one use `citar-citeproc-format-reference` to use arbitrary CSL styles, and so to do as in `org-bib`.

https://github.com/emacs-citar/citar/commit/97092df80e4a9adcce0f9888a079aaecaac5438a

But I'm also thinking of just allowing, in both `citar` and in `citar-org-roam`, users to configure to use `citeproc` in place of the citar templates. 

In practice, then, they would be able to choose a CSL style, and that would become the title content.

But I still need to sort out details; not just whether to do it, but how.

https://github.com/emacs-citar/citar/issues/740
