### ISSUE TITLE
Add additional information from bibliographic entry into note, with pre-defined formatting?

### ISSUE THREAD

**Issue by johkneisl** [pprevos/citar-denote#16]
It seems like citar-denote already has all the functionality to read an entry in a bibliography,
and write its data to a note in denote, e.g. the citation key in the note or the authors/years/title as the note's filename.
This is awesome, but right now it seems like this functionality can only be utilized in a very narrow way.
It would be great to use this functionality a bit more flexibly.

What a lot of people do with similar note-taking apps, is to create notes for an entry in their bibliography,
such that basic pre-definable information about the bibliographic entry is written into the note automatically.
For example, I choose an entry just like I do right now with citar-denote, and citar-denote creates a note,
just as it already does. But in addition to writing the citation key in the front matter, I'd like it to write something
like

``` 
author: NAME
date: DATE
publisher: PUBLISHER 
isbn: ISBN
pages: PAGES
arXiv: ARXIV
```

underneath or in the denote front matter (don't know if denote limits what can go in the FM), 
where the uppercase variables are read from the bibliography, and the exact information to be displayed 
is configurable via the citar-denote package. I hope it's clear what I'm asking.

Meaningful use cases: 

- Adding the ISBN or arXiv identified makes rediscovery future-proof. Opposite to citation keys, it's not going to change or break. Even if citar-denote or denote itself should go away in the future, a literature note can be uniquely identified with a simple `grep` for its ISBN.

- One might want to create a note for every author one's reading in one's note-taking app (here denote), and link to them, such that visiting the author's note and displaying backlinks informs one about all previous times someone has read something by them. Having the author there takes away manual work.

**Comment by pprevos** [comment]
Hi @johkneisl,

It is possible to add additional front matter. That is not with Denote, but a function of either Org Mode or Markdown. Plain text has no rules.

In both Markdown and Org Mode, the author is reserved for the author of the file and title is the title of the file (which can be the same as the title of the literature). 

What would the purpose be or repeating the data from your BibTeX file in the note? You can easily access this information via Citar. We have [Issue 13](https://github.com/pprevos/citar-denote/issues/13) which aims to make it easier to view the bibliographic data related to references.

**Comment by pprevos** [comment]
Another reason we cannot implement the functionality you suggested is that Citar-Denote allows multiple references per note. Also, adding metadata to the front-matter duplicates information, creating synchronisation issues between the note and bibliography files.

This new function lets you access the bibliographic entry in the original source. This function opens the bibliographic entry associated with the note.  It will be added to the next release.

```
  (defun citar-denote-open-reference-entry ()
    "Open  attachments, notes and links associated with a bibliographic note."
    (interactive)
    ;; Any citation keys in the note?
    (if-let ((keys (citar-denote-retrieve-references (buffer-file-name)))
             (key (citar-select-ref
                   :filter (citar-denote-has-citekeys keys))))
            (citar-open-entry key)
      (if (denote-file-is-note-p (buffer-file-name))
          (when (yes-or-no-p "Current buffer does not reference a citation key.  Add a reference? ")
            (citar-denote-add-citekey)
            (citar-denote-dwim))
        (user-error "Buffer is not a Denote file"))))
```

**Comment by johkneisl** [comment]
Thanks, makes sense to me.
I just switched from non-emacs software, I think I stumbled into citar-denote too quickly, 
before really looking into the power of citar (and emacs) first.
The new function seems useful to me.

**Comment by pprevos** [comment]
Good move,

Emacs is quite different to other software. Everything is modular like a box of Lego. Every package builds on others.

Perhaps [my website](https://lucidmanager.org/tags/emacs/) is useful (will soon include Denote).

P:)
