### ISSUE TITLE
add an easy way to insert a link to the note of a given reference?

### ISSUE THREAD

**Issue by JonatanSahar** [pprevos/citar-denote#20]
Hi,
I appreciate the work you've put into this, and I think it's great.
I think it would be really useful to be able to quickly insert a link to the note attached to a given reference. 
I imagine using the same interface as citar-denote-open-note, but inserting a denote link instead.

**Comment by pprevos** [comment]
Hi Jonatan,

Great suggestion. I will add this functionality over the next week or so.

You are right to follow the process of `citar-denote-open-note` and then pass the notes files (can be more than one) into the `denote-link function`.

Peter

**Comment by pprevos** [comment]
Hi Jonatan,

Would this function meet your needs?

```
(defun citar-denote-link-reference ()
  "Insert a Denote link to a bibliographic note."
  (interactive)
  (if-let* ((citekey (citar-select-refs
		      :filter (citar-denote-has-notes)
		      :multiple nil))
	    (files (gethash (car citekey)
			    (citar-denote-get-notes citekey)))
	    (file (if (= (length files) 1)
		      (car files)
		    (funcall project-read-file-name-function
			     "Select note: "
			     files nil nil nil))))
      (denote-link file)))
```

**Comment by JonatanSahar** [comment]
That's exactly what I had in mind! thanks!
there's something a little off though - the code above is missing one reference note.

These are the current bibliographic notes:
![image](https://user-images.githubusercontent.com/18332012/229466749-3828d438-3cee-43ad-a89c-dbcb2da48703.png)
 
and this is what `citar-denote-link-reference` gives:

![image](https://user-images.githubusercontent.com/18332012/229466607-e4b86b68-f541-4c30-8b89-a40a4699420f.png)


Any thoughts?

**Comment by pprevos** [comment]
Hmm, that's weird.

What do you get when using `citar-denote-open-note`?

Jonathan Sahar ***@***.***> writes:

> That's exactly what I had in mind! thanks!
> there's something a little off though - the code above is 
> missing one reference note.
>
> These are the current bibliographic notes:
> image 
>
> and this is what citar-denote-link-reference gives:
>
> image 
>
> Any thoughts?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were assigned.


-- 
Dr Peter Prevos
---------------
peterprevos.com

**Comment by pprevos** [comment]
Are all files saved to disk?

**Comment by JonatanSahar** [comment]
you're quick! I edited to remove it like 2 two minutes after posting :)
the note was somehow not connected to the ref. It workd beutifully.

**Comment by pprevos** [comment]
Thanks for the suggestion and the feedback.

The email still contained your images so that is what I responded to.

I have committed the new version, which will appear in MELPA any time soon.  Commit: 327c7f3
