### ISSUE TITLE
double "#+title" in notes created throught the citar interface 

### ISSUE THREAD

**Issue by JonatanSahar** [pprevos/citar-denote#21]
Hi, 
Thanks for your work on this, it's really great and I use it daily :)
I have this strange bug, the source of which I can't figure out:

![image](https://github.com/pprevos/citar-denote/assets/18332012/4b240c52-eef6-47a6-bf8c-5316505a5c34)

This only happens with notes I create hrough citar (either `citar-create-note`, or throught `citar-open`, and then the "create denote" action).

Thanks for your assistance.

**Comment by JonatanSahar** [comment]
I've set my `citar-templates`  to

> ((main . "${author editor:30}     ${date year issued:4}     ${title:48}")
>  (suffix . "         ${tags keywords keywords:*}   ${=key= id:15}    ${=type=:12}")
>  (preview . "${author editor} (${year issued date}) ${title}, ${journal journaltitle publisher container-title collection-title}.\n")
>  (note . ""))

and it persists. Before I had 
>(note . "Notes on ${author}, ${title}")

but that had no effect, as the title was taken from the prompt oferred which was populated with the title, in accordance with `citar-denote-title-format`

**Comment by pprevos** [comment]
Hi Jonatan,

I am glad the package is helpful to you.

This behaviour does not occur in my workflow. I use `citar-open` in most cases. 

The `citar-denote-create-note` function creates new notes. This function does not use `citar-templates` but invokes the `denote` function. 

My config is here: https://github.com/pprevos/emacs-config/blob/main/emacs-configuration.org

Lets try to isolate the cause.

P:)

**Comment by JonatanSahar** [comment]
that's very strange, so `citar-denote-create-note` just passes the requested file title, without the #+title? what would make denote do this..? it's also strange the way the whole top of the file gets marked.

**Comment by pprevos** [comment]
Hi Jonatan,

The string `"#+title:"` does not appear anywhere in the `citar-denote` source code. The package generates notes using the `denote` function from the Denote package. My package inserts a generated title and keywords with an optional subdirectory. It then adds the reference key to the front matter. 

Do you use Denote templates? Did you insert the string `"#+title:"` in these by any chance?

**Comment by pprevos** [comment]
Hi Jonathan,

Has this issue been resolved?

P:)

**Comment by JonatanSahar** [comment]
Hi, unfortunately not..

**Comment by pprevos** [comment]
Hi Jonatan,

I am unable to replicate your issues. 

What is the value of the `denote-prompts` variable? Do you use a Denote template?

Also, are you using the latest version of Denote and Citar-Denote?

I have tried to replicate your problems with this minimal install, but everything works fine with new note creation. Could you find which part of your config causes the issue?

```
;; Minimum citar-denote configuration
;; Assumes all required packages are installed

;; Use-package
(package-initialize)
(require 'use-package)

;; Citar
(use-package citar ;; version 
  :custom
  ;; Location of bibliography
  (citar-bibliography '("~/Documents/library/lucidmanager.bib")))

;; Denote
(use-package denote
  :custom
  ;; Folder where Denote files lives
  (denote-directory "~/Documents/notes/"))

;; Citar-denote
(use-package citar-denote
  :init (citar-denote-mode))

;; Mini Buffer Completion
  ;; Enable vertico
  (use-package vertico
    :init
    (vertico-mode)
    :custom
    (vertico-sort-function 'vertico-sort-history-alpha))
```

**Comment by pprevos** [comment]
Unable to replicate.
