### ISSUE TITLE
citar-denote-generate-title: Wrong number of arguments: (1 . 1), 3

### ISSUE THREAD

**Issue by JonatanSahar** [pprevos/citar-denote#22]
when setting `citar-denote-title-format` to "author-year-title" I get the following error:

> citar-denote-generate-title: Wrong number of arguments: (1 . 1), 3

which I don't get when setting it to "title"

**Comment by pprevos** [comment]
Hi Jonathan,

I am investigating this issue. 

Can you share your config for citar, denote and citar-denote? I can't replicate this error.

Perhaps try this minimum configuration:

```
;; Minimum citar-denote configration

;; Use-package
(package-initialize)
(require 'use-package)

;; Citar
(use-package citar
  :custom
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  (citar-bibliography '("~/Documents/library/lucidmanager.bib")))

;; Denote
(use-package denote
  :custom
  (denote-directory "~/Documents/notes/")
  :hook
  (dired-mode-hook . denote-dired-mode))

;; Citar-denote
(use-package citar-denote
  :init (citar-denote-mode))

(use-package vertico
  :init
  (vertico-mode))
```

P:)

**Comment by JonatanSahar** [comment]
Thank you. 
I'll try the minimal config, meanwhile, here is my current config:

> (after! citar
>   (setq! citar-bibliography (my/get-bib-file-list)
>    citar-at-point-function 'embark-act
>    citar-file-note-org-include '(org-id org-roam-ref)
>    citar-notes-paths literature-notes-dir
>    citar-library-paths (list "~/Documents/bibliography")
>   ;; (add-to-list 'citar-file-open-functions '("pdf" . citar-file-open-external))
>   citar-templates '((main . "${author editor:30}     ${date year issued:4}     ${title:48}")
>                           (suffix . "         ${tags keywords keywords:*}   ${=key= id:15}    ${=type=:12}")
>                           (preview . "${author editor} (${year issued date}) ${title}, ${journal journaltitle publisher container-title collection-title}.\n")
>                           (note . "")))
> 
>   (setq citar-symbols
>         `((file . (,(all-the-icons-icon-for-file "foo.pdf" :face 'all-the-icons-dred) .
>                    ,(all-the-icons-icon-for-file "foo.pdf" :face 'citar-icon-dim)))
>           (note . (,(all-the-icons-icon-for-file "foo.txt") .
>                    ,(all-the-icons-icon-for-file "foo.txt" :face 'citar-icon-dim)))
>           (link .
>                 (,(all-the-icons-faicon "external-link-square" :v-adjust 0.02 :face 'all-the-icons-dpurple) .
>                  ,(all-the-icons-faicon "external-link-square" :v-adjust 0.02 :face 'citar-icon-dim)))))
>   ;; Here we define a face to dim non 'active' icons, but preserve alignment
>   (defface citar-icon-dim
>     '((((background dark)) :foreground "#282c34")
>       (((background light)) :foreground "#fafafa"))
>     "Face for obscuring/dimming icons"
>     :group 'all-the-icons-faces)
> 
>  (defun citar-open-library-file (key-entry)
>     "Open library file associated with the KEY-ENTRY.
> 
> With prefix, rebuild the cache before offering candidates."
>     (interactive (list (citar-select-ref
>                         :rebuild-cache current-prefix-arg)))
>     (let ((embark-default-action-overrides '((file . citar-file-open-external))))
>       (message "embark-default-action-overrides %s" embark-default-action-overrides)
>       (when (and citar-library-paths
>                  (stringp citar-library-paths))
>         (error "Make sure 'citar-library-paths' is a list of paths"))
>       (citar--library-file-action key-entry 'open)))
> 
>   (defun citar--library-file-action (key-entry action)
>     "Run ACTION on file associated with KEY-ENTRY."
>     (let* ((fn (pcase action
>                  ('open 'citar-file-open-external 'citar-file-open)
>                  ('attach 'mml-attach-file)))
>            (ke (citar--ensure-entries key-entry))
>            (key (caar ke))
>            (entry (cdar ke))
>            (files
>             (citar-file--files-for-entry
>              key
>              entry
>              citar-library-paths
>              citar-file-extensions))
>            (file
>             (pcase (length files)
>               (1 (car files))
>               ((guard (> 1))
>                (citar-select-file files)))))
>       (if file
>           (funcall fn file)
>         (message "No associated file"))))
>   )
> 
> (use-package! denote
>   :config
>   ;; Remember to check the doc strings of those variables.
> (setq! denote-directory (expand-file-name "~/notes/")
>  denote-known-keywords '("emacs" "thesis")
>  denote-infer-keywords t
>  denote-sort-keywords t
>  denote-prompts '(title keywords)
>  denote-excluded-directories-regexp nil
>  denote-excluded-keywords-regexp nil)
> 
>   ;; Pick dates, where relevant, with Org's advanced interface:
>   (setq denote-date-prompt-use-org-read-date t)
> 
> 
>   ;; Read this manual for how to specify `denote-templates'.  We do not
>   ;; include an example here to avoid potential confusion.
> 
>   ;; We allow multi-word keywords by default.  The author's personal
>   ;; preference is for single-word keywords for a more rigid workflow.
>   (setq denote-allow-multi-word-keywords t)
> 
>   (setq denote-date-format nil) ; read doc string
> 
>   ;; By default, we do not show the context of links.  We just display
>   ;; file names.  This provides a more informative view.
>   (setq denote-backlinks-show-context t)
> 
>   ;; Also see `denote-link-backlinks-display-buffer-action' which is a bit
>   ;; advanced.
> 
>   ;; If you use Markdown or plain text files (Org renders links as buttons
>   ;; right away)
>   (add-hook 'find-file-hook #'denote-link-buttonize-buffer)
> 
>   ;; We use different ways to specify a path for demo purposes.
>   (setq denote-dired-directories
>         (list denote-directory
>               (thread-last denote-directory (expand-file-name "attachments"))
>               (expand-file-name "~/Documents/books")))
> 
>   ;; Generic (great if you rename files Denote-style in lots of places):
>   ;; (add-hook 'dired-mode-hook #'denote-dired-mode)
>   ;;
>   ;; OR if only want it in `denote-dired-directories':
>   (add-hook 'dired-mode-hook #'denote-dired-mode-in-directories)
> 
>   ;; Here is a custom, user-level command from one of the examples we
>   ;; showed in this manual.  We define it here and add it to a key binding
>   ;; below.
>   (defun my-denote-journal ()
>     "Create an entry tagged 'journal', while prompting for a title."
>     (interactive)
>     (denote
>      (denote--title-prompt)
>      '("journal")))
> 
>   ;; Denote DOES NOT define any key bindings.  This is for the user to
>   ;; decide.  For example:
> 
> 
>   (with-eval-after-load 'org-capture
>     (setq denote-org-capture-specifiers "%l\n%i\n%?")
>     (add-to-list 'org-capture-templates
>                  '("n" "New note (with denote.el)" plain
>                    (file denote-last-path)
>                    #'denote-org-capture
>                    :no-save t
>                    :immediate-finish nil
>                    :kill-buffer t
>                    :jump-to-captured t)))
>   )
> 
> (use-package! citar-denote
>   :init
>   (citar-denote-mode)
>   (defun citar-denote-link-reference ()
>     "Insert a Denote link to a bibliographic note."
>     (interactive)
>     (if-let* ((citekey (citar-select-refs
>                         :filter (citar-denote-has-notes)
>                         :multiple nil))
>               (files (gethash (car citekey)
>                               (citar-denote-get-notes citekey)))
>               (file (if (= (length files) 1)
>                         (car files)
>                       (funcall project-read-file-name-function
>                                "Select note: "
>                                files nil nil nil))))
>         (denote-link file))))

**Comment by pprevos** [comment]
Thanks,

I like `(citar-denote-link-reference)`. I filter for `_bib` when looking for a literature note.

What is the `after!` function at the start?

**Comment by JonatanSahar** [comment]
it's a Doom macro (function?) which runs the inclosed command only after a
package has been loaded.

**Comment by JonatanSahar** [comment]
glad you like it, I thought it was yours to begin with :)
I don't remember where I got that from then..

**Comment by pprevos** [comment]
How did you go trying the minimum install? I don't know anything about Doom Emacs.

**Comment by JonatanSahar** [comment]
Hi,
I've been too busy with work lately to try it yet.. hope to get to it soon.

**Comment by pprevos** [comment]
Unable to replicate issue.
