### ISSUE TITLE
Possibility of multiple "bibliographic notes" per file

### ISSUE THREAD

**Issue by krisbalintona** [pprevos/citar-denote#26]
Basically, is there an easy way to have two or more references/bibliographic entries use the same note file?

The practical use case for me is when I have the same work but from different translators. I'd like to have my notes for each translation in the same file.

**Comment by pprevos** [comment]
Hi Kristoff,

Yes, you can have one one with many references and vice versa. So you can create a note for each chapter of a book, or conduct a full literature review in one note - your choice.

But you need to set `citar-open-always-create-notes` to `nil`.

Feel free to contact me with any other issues. The [online manual](https://lucidmanager.org/productivity/bibliographic-notes-in-emacs-with-citar-denote/) discusses every option.

P:)
