### ISSUE TITLE
“Buffer is not a Denote file” Error

### ISSUE THREAD

**Issue by n12k0** [pprevos/citar-denote#27]
I encounter an error stating `Buffer is not a Denote file` every time I attempt to insert a citation using `citar-denote`, despite trying multiple configurations. Including the one here: https://github.com/pprevos/citar-denote/blob/6e236e9100d1401cd7c628c5f799badded77967d/test/init.el

I am on Windows and just did a fresh install, so I am sure there is nothing else interfering. 

Would appreciate some help!

Thank you

**Comment by pprevos** [comment]
Is the active buffer a Denote file? The various Citar-Denote functions that only work for a Denote file test whether `(denote-file-is-note-p (buffer-file-name))` is `t`.

Which function did you use when the error occurred?

**Comment by n12k0** [comment]
Thanks for answering! I think I managed to pinpoint the problem. Apparently, the Denote Notes, are only recognized after they are saved. Otherwise, it won't work. 
Again thank you very much!

**Comment by pprevos** [comment]
That is a relief! You can change Denote's behaviour by customising `denote-save-buffer-after-creation`.

Let me know whether everything works fine.

**Comment by n12k0** [comment]
Ah, nice! I will certainly do that. Thank you, again!
