### ISSUE TITLE
Notes linked using `citar-denote-add-citekey` are not visitable

### ISSUE THREAD

**Issue by swflint** [pprevos/citar-denote#28]
Using the following `citar-denote` configuration

```elisp
(add-directory-to-load-path "citar-denote")
(require 'citar-denote)
(setopt citar-denote-keyword "literature"
        citar-denote-subdir "literature"
        citar-denote-template t)
(citar-denote-mode)
(diminish 'citar-denote-mode)
```

Existing notes that were linked using `citar-denote-add-citekey` are not detected as existing.  Have I missed some piece of configuration?

**Comment by swflint** [comment]
Moreover, I've noticed that creation of new notes does not create valid notes: it creates empty files with no denote frontmatter.

**Comment by pprevos** [comment]
Hi Samuel, I will investigate and use your code this later today.

What does the diminish function do? Is `citar-denote` mode activated?

**Comment by swflint** [comment]
`citar-denote-mode` is activated.  `(diminish 'citar-denote-mode)` prevents `citar-denote` from cluttering the modeline (i.e., it removes the lighter).

**Comment by pprevos** [comment]
I tried this with an unconfigured Emacs but cannot replicate your issue. Which package do you use for the `add-directory-to-load-path` function and `diminish` function?

**Comment by swflint** [comment]
`add-directory-to-load-path` is a small shim over `add-to-load-path` and `expand-file-name`, it's equivalent to `(add-to-list 'load-path (expand-file-name "citar-denote" (file-name-directory (user-init-file))))`.  Diminish comes from [here](https://github.com/myrjola/diminish.el.git).

**Comment by pprevos** [comment]
Thanks for the clarification. I will try to replicate the error tonight.

Based on your feedback, the next version of Citar Denote has no lighter string. I agree it is pointless.

**Comment by pprevos** [comment]
Hi, I am working through your config. 

Firstly, `citar-denote-subdir` is a boolean as it instructs Denote to ask for a directory. Perhaps I can enhance the code to take a string and make it a predefined subdir in `denote-directory` in a future version.

I think I found the issue for the system not recognising the new bib keyword. I fixed it in the most recent version ([88a7fd2](https://github.com/pprevos/citar-denote/commit/88a7fd2e219e860894e2a4a3e336315cb40fd110)).

This is the init I used:
```
(use-package diminish :ensure t)
(add-to-list 'load-path (expand-file-name "citar-denote" user-emacs-directory))
(require 'citar-denote)
(setopt citar-denote-keyword "literature"
        citar-denote-subdir "literature"
        citar-denote-template t
	denote-templates
	'((literature . "* Abstract\n")))
(citar-denote-mode)
;; (diminish 'citar-denote-mode) ;; no longer required
```

Can you please confirm if this works for you?

**Comment by swflint** [comment]
Wonderful!  That works.  Now to get ebib to integrate with it...

As a note, the customization type on `citar-denote-subdir` is a bit generic.  Perhaps a different type (shown below) would improve discoverability/use of customize?
```elisp
(defcustom citar-denote-subdir nil
  "Ask for or save in a subdirectory when creating a new bibliographic note.

- `nil', note is stored in `denote-directory'.
- `t', Denote asks for subdirectory to store the note.
- `string': When entering a string, the note is save in a subdirectory under
  `denote-directory'."
  ;; https://github.com/pprevos/citar-denote/issues/11
  :group 'citar-denote
  :type  '(choice (const :tag "Stored in `denote-directory'." nil)
                  (const :tag "Ask for subdirectory to store note." t)
                  (string :tag "Save in specific subdirectory.")))
```

**Comment by pprevos** [comment]
Excellent, I am glad we got that fixed. Good suggestion on the subdir variable. It will appear in the next version, or you can suggest it as a pull request to get formal credit for the contribution.

Integrating Denote with ebib requires a whole new package as it has a different engine for managing relationships between BibTex files and notes.
