### ISSUE TITLE
citar-denote-find-cites doesn't include files with only '#+reference:'

### ISSUE THREAD

**Issue by EFLS** [pprevos/citar-denote#34]
When calling `citar-denote-find-cites` on a bibliographic entry, the results don't include files only mention the bibtex key in the `#+reference` front-matter (and don't cite the bibtex key @-style in the body of the text).

The reason being that `citar-denote--retrieve-cite-files` includes a `@` sign in the xref query.

Is this intended behaviour? If not, then this might be a bug. If this is intentional, I can prepare a PR that introduces a custom variable `citar-denote-cite-includes-reference` to make this customizable.

**Comment by pprevos** [comment]
Hallo Elias,

`citar-denote-find-citations` finds files that cite an entry in the text. Finding references is through `citar-denote-open-note`.

In this package I have separated references from citations. 

Perhaps it could be useful to combine these approaches. Happy to make the function configurable.

We could even go more radical and recognise any citation, not just the font matter, as a bibliographic note in Citar, which requires a rewrite of `citar-denote--get-notes`.

Groeten

Peter

**Comment by EFLS** [comment]
Dag Peter

Bedankt. That makes sense. I made PR #35 to make this an option to the user. So the default stays the same, but one could choose to consider a 'reference' a citation as well.

My reasoning behind this is that, starting from a bibtex key, I want to quickly see which note discusses this bibliographic entry (either by citing it, but also just by mentioning it in the front matter -- I don't always include an '@' citation in those notes' bodies).

**Comment by pprevos** [comment]
Bedankt,

I get the reasoning. I'll review and merge the changes on my day off tomorrow.

`citar-denote--get-nocite` already includes citations and references. I might have to make this also configurable.

It has made me rethink wether we could make it possible to classify all notes that contain a citation as a bibliographic note by modifying `citar-denote--get-notes`. However, only Org mode can contain citations, people who use Markdown and Org mode can only se reference lines. It could also slow down the system as the search space becomes all notes.

P:)

**Comment by pprevos** [comment]
c2da73e
