### ISSUE TITLE
Can denote replace org-noter?

### ISSUE THREAD

**Issue by zenny** [pprevos/citar-denote#42]
Hi @pprevos ,

Learning EWS slowly.

EWS have `denote` by default. Can `denote` be reconfigured to do the same like [org-noter](https://github.com/org-noter/org-noter) with relevant [video presentations](https://www.youtube.com/watch?v=HCOXva1Ndfk) (2023) and [https://www.youtube.com/watch?v=P02FD63gGco] (2022) where `org-noter` is used to create anki and also to immutably annotate pdf,djvu,epub documents]? 

Any inputs on reconfiguring denote/denote-citar to achieve same effects without breaking EWS default configuration? Thanks.

Cheers,
/zenny

**Comment by pprevos** [comment]
I have reviewed Org Noter and decided not to implement this functionality in EWS. You can of course add it to your own config if you choose to do so.

The Citar-Denote package can link Org mode files to bibliography attachments.

**Comment by zenny** [comment]
> I have reviewed Org Noter and decided not to implement this functionality in EWS.

@pprevos Thanks. I just noted this lately.

> You can of course add it to your own config if you choose to do so.

Any pointer to config org-noter without breaking ews? 

In case ews already has alternative to org-noter, please let me know.

> 
> The Citar-Denote package can link Org mode files to bibliography attachments.

How does citar-denote integrates with the bibliography from Zotero? Just curious.

Cheers and belated new year wishes,
/zenny

**Comment by pprevos** [comment]
Hi Zenny,

In Zotero, install the Better BibTex package.

With that package you can create a BibTex file that is continuously updated.

Add that file to `ews-bibtex-directory` and run `ews-bibtex-register`

Attachments should work fine as well.

have a great `(let ((year 0)) (mapcar (lambda (x) (setq year (+ year x))) (mapcar (lambda(n) (expt n 3)) (number-sequence 1 9))) year)`

P:)
