### ISSUE TITLE
citar-denote-remove-citekey reports error because citar-denote--remove-bibkey is imcompatible with denote 3.0.0

### ISSUE THREAD

**Issue by goofansu** [pprevos/citar-denote#43]
Error: `citar-denote--remove-bibkey: Wrong number of arguments: #<subr denote-rename-file-using-front-matter>, 2`

References:
- https://github.com/pprevos/citar-denote/blob/c0c467653976ab40ff330fcb4586fadb69e48a29/citar-denote.el#L304
- https://github.com/protesilaos/denote/blob/3.0.0/denote.el#L3210

**Comment by pprevos** [comment]
Only just found the time to look into this. 

Fixed with [66fd7a8](https://github.com/pprevos/citar-denote/commit/66fd7a87d715631625d470bc0f9104178f39cef6)

**Comment by goofansu** [comment]
@pprevos Thank you! Your work really make my literature note-taking much easier.
